apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-hw-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: ocr-hw-backend
  template:
    metadata:
      labels:
        app: ocr-hw-backend
    spec:
      containers:
        - name: ocr-hw-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.APP_VERSION }}"
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.backend.port }}"
            - name: KAFKA_BROKER
              value: "{{ .Values.infra.kafkaBroker }}"
            - name: WS_GATEWAY_URL
              value: "http://ocr-hw-ws-gateway:{{ .Values.wsGateway.port }}"
            - name: ENABLED_ORIGINS
              value: "{{ .Values.backendConfig.enabledOrigins }}"
            - name: OCR_API_KEY
              value: "{{ .Values.backendConfig.ocrApiKey }}"
            - name: DATABASE_HOST
              value: "{{ .Values.infra.database.host }}"
            - name: DATABASE_PORT
              value: "{{ .Values.infra.database.port }}"
            - name: DATABASE_USER
              value: "{{ .Values.infra.database.user }}"
            - name: DATABASE_PASS
              value: "{{ .Values.infra.database.password }}"
            - name: DATABASE_NAME
              value: "{{ .Values.infra.database.name }}"
            - name: S3_PROTOCOL
              value: "{{ .Values.backendConfig.s3.protocol }}"
            - name: S3_PUBLIC_URL
              value: "{{ .Values.backendConfig.s3.publicUrl }}"
            - name: S3_ENDPOINT
              value: "{{ .Values.backendConfig.s3.endpoint }}"
            - name: S3_PORT
              value: "{{ .Values.backendConfig.s3.port }}"
            - name: S3_BUCKET
              value: "{{ .Values.backendConfig.s3.bucket }}"
            - name: S3_USE_SSL
              value: "{{ .Values.backendConfig.s3.useSsl }}"
            - name: S3_ACCESS_KEY
              value: "{{ .Values.backendConfig.s3.accessKey }}"
            - name: S3_SECRET_KEY
              value: "{{ .Values.backendConfig.s3.secretKey }}"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
