apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-hw-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: ocr-hw-frontend
  template:
    metadata:
      labels:
        app: ocr-hw-frontend
    spec:
      containers:
        - name: ocr-hw-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.APP_VERSION }}"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://ocr-hw-backend:{{ .Values.backend.port }}"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
