apiVersion: v1
kind: Service
metadata:
  name: ocr-hw-ocr-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ocrService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ocr-hw-ocr-service
