apiVersion: v1
kind: Service
metadata:
  name: ocr-hw-ws-gateway
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.wsGateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ocr-hw-ws-gateway
