name: Test, build and release

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
  FRONTEND_IMAGE: ocr-hw-frontend
  BACKEND_IMAGE: ocr-hw-backend

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd ./ocr_backend
          npm ci

      - name: Run unit tests
        run: |
          cd ./ocr_backend
          npm run test -- --passWithNoTests

  lint-test:
    name: Lint test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd ./ocr_backend
          npm ci

      - name: Run ESLint
        run: |
          cd ./ocr_backend
          npm run lint

  build-and-push:
    needs: [unit-test, lint-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build and push frontend image
        run: |
          cd ./ocr_frontend
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Build and push backend image
        run: |
          cd ./ocr_backend
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }} .
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Update values.yaml
        run: |
          cd ./helm
          sed -i '/ocr-hw-frontend/{n;s|APP_VERSION:.*|APP_VERSION: ${{ github.sha }}|}' values.yaml
          sed -i '/ocr-hw-backend/{n;s|APP_VERSION:.*|APP_VERSION: ${{ github.sha }}|}' values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update image versions to ${{ github.sha }}"
          git push